version: '3.8'

services:
  ocr-backend-staging:
    image: localhost:5000/stellar-ocr-backend:${IMAGE_TAG:-latest}
    ports:
      - "5011:5000"
    environment:
      - FLASK_ENV=staging
    restart: unless-stopped
    labels:
      - "environment=staging"
      - "service=ocr-backend"
    
  ner-service-staging:
    image: localhost:5000/stellar-ocr-ner:${IMAGE_TAG:-latest}
    ports:
      - "5012:5002"
    environment:
      - FLASK_ENV=staging
    restart: unless-stopped
    labels:
      - "environment=staging"
      - "service=ner"
    
  frontend-staging:
    image: nginx:alpine
    ports:
      - "3001:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    restart: unless-stopped
    labels:
      - "environment=staging"
      - "service=frontend"
